name: schema_validation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  schema_validation:
    strategy:
      matrix:
        dbversion: [ "postgres:latest" ]
        go: [ "1.17" ]
        platform: [ ubuntu-latest ] # can not run in macOS and widnowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the policy directory
        uses: actions/checkout@v2

      - name: Cache CQ
        id: cache-cq-binary
        uses: actions/cache@v2
        with:
          path: cloudquery
          key: ${{ runner.os }}-${{ hashFiles('cloudquery') }}

      - name: Download Cloudquery
        if: steps.cache-cq-binary.cache-hit != 'true'
        run: |
          curl -L https://github.com/cloudquery/cloudquery/releases/latest/download/cloudquery_Linux_x86_64 -o cloudquery
          chmod a+x cloudquery
        env:
          OS: Linux

      - name: Build Schema
        run: |
          ./cloudquery provider build-schema azure --config ./test/policy_cq_config.hcl --enable-console-log
        env:
          CQ_NO_TELEMETRY: 1

      - name: Policy Run
        run: |
          ./cloudquery policy run . --config ./test/policy_cq_config.hcl --enable-console-log
        env:
          CQ_NO_TELEMETRY: 1